### ISSUE TITLE
Display Reclaim and Donate Buttons when funding target is not reached

### ISSUE THREAD

**Issue by BartuCulha** [thesphere/karmic-dapp#22]
Users should be able to reclaim their ETH or Donate their ETH when the funding target is not reached
Expected:
![Frame 3](https://user-images.githubusercontent.com/24368665/155140610-e84ff46f-eec7-401f-811c-5815084de2c3.png)

Result:
![The Sphere (4)](https://user-images.githubusercontent.com/24368665/155140684-5a4fb316-eb29-404e-be22-e2f0dedc537a.png)

**Comment by codebuster22** [comment]
did you approve all the tokens first?
