### ISSUE TITLE
Cliking Donate ETH Button should display a Pop-up

### ISSUE THREAD

**Issue by BartuCulha** [thesphere/karmic-dapp#28]
When you click Donate button we should be seeing a pop up that informs the user about donatable ETH and how many KARMIC tokens the user is going to receive after the donation. In our dapp the user is directed to metamask which should come after confirming our dapp's pop-up

Expected:
![Home](https://user-images.githubusercontent.com/24368665/155304072-6e817512-bc7f-495c-81ab-79dfbd97d53a.png)

**Comment by BartuCulha** [comment]
- [ ] Increase width to make "Claim Karmic Tokens" text one-liner. (Optional: if we can make the width size equal to all other pop ups it will be great)
- [ ] Change copy text to: "Donate your ETH to the Sphere Pool to receive KARMIC tokens"
- [ ] Align Donate and close button to the middle 

Expected:
![Pop-Up](https://user-images.githubusercontent.com/24368665/155716852-f81b398d-34bf-4cd5-a85d-fe0a525bfae5.png)


Result:
![The-Sphere (2)](https://user-images.githubusercontent.com/24368665/155716676-77ff8ed6-0c44-4960-8bf6-fea128c869e2.png)

**Comment by codebuster22** [comment]
added a fix
