### ISSUE TITLE
Box Tokens after Reclaiming ETH needs readjustments

### ISSUE THREAD

**Issue by BartuCulha** [thesphere/karmic-dapp#29]
After Reclaiming my ETH, I had to refresh the page to see the changes.

- [ ] Automatically display the changes after a successful transaction
- [ ] Show the Reclaimed ETH and the amount
- [ ] Text copy to say: You have successfully reclaimed all of your ETH.

Expected
![Frame 3 (1)](https://user-images.githubusercontent.com/24368665/155321867-78f35cda-c6f8-4298-a3e7-33cb1ab87fad.png)

Result:
![The Sphere (10)](https://user-images.githubusercontent.com/24368665/155321876-c090a755-3e29-4ed9-87f8-c4b4c1fb7f44.png)

**Comment by codebuster22** [comment]
Hey, so it will be an extra effort to see if a user have reclaimed the eth or not (Going through events and filtering the queries)
Can we come up with a generic copy, that says something like "Nothing remaining to claim"

**Comment by BartuCulha** [comment]
can we not display "You have successfully reclaimed all of your ETH." even if we dont check the events and filtering the queries. My suggestion is to display something positive.

**Comment by codebuster22** [comment]
it might happen that user never had contributed
