### ISSUE TITLE
Successful Box Tokens needs adjustments

### ISSUE THREAD

**Issue by BartuCulha** [thesphere/karmic-dapp#31]
Before Approving Karmic Tokens

- [ ] Copy Text to say: "In order to receive KARMIC tokens, please approve your tokens first and then claim them."
- [ ] Display Claimable Karmic Tokens and the amount

Expected:
![Frame 43](https://user-images.githubusercontent.com/24368665/155323369-0d411e59-87ec-44b5-9b1c-c9ae521340da.png)

Result:
![The Sphere (5)](https://user-images.githubusercontent.com/24368665/155324029-f8c67602-f01f-4126-900d-036920bc308f.png)

After Approving Karmic Tokens

- [ ] Display Claimable Karmic Tokens and the amount
- [ ] Change Copy text to: "You can claim your KARMIC Tokens.

Result:
![The Sphere (12)](https://user-images.githubusercontent.com/24368665/155325881-78323552-5886-4794-8824-e88d869040ca.png)

**Comment by codebuster22** [comment]
> After Claiming Karmic Tokens

 Display Claimable Karmic Tokens and the amount
 Change Copy text to: "You can claim your KARMIC Tokens.

Don't you think, after claiming, there's nothing to claim anymore.

**Comment by BartuCulha** [comment]
sorry changed claiming with approving. my bad

**Comment by codebuster22** [comment]
Cool, have solved it though
